// Static content generated by convertData.cjs from Strapi export
import { Blog, Event, Member, Coordinator, Activity } from '../types';

export const coordinators: Coordinator[] = [
  {
    "id": "121",
    "name": "John Bethlehem Pallan",
    "role": "Charter Secretary",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/johnbethlehm/",
      "linkedin": "https://in.linkedin.com/in/johnbethlehempallan",
      "facebook": ""
    },
    "image": "/coordinators/john-bethlehem-pallan.jpg"
  },
  {
    "id": "123",
    "name": "Nathan Zacharia Saby",
    "role": "Charter Treasurer",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/nathan_zach?igsh=MWhzMTd4dDh1dnkxeQ==",
      "linkedin": "https://www.linkedin.com/in/nathan-z-saby",
      "facebook": ""
    },
    "image": "/coordinators/nathan-zacharia-saby.jpg"
  },
  {
    "id": "125",
    "name": "Zayan M S",
    "role": "Charter Vice President",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/zayan_378?igsh=d2s3bmpxbGZoZG8w",
      "linkedin": "https://www.linkedin.com/in/zayan-ms-558329328?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      "facebook": ""
    },
    "image": "/coordinators/zayan-m-s.jpg"
  },
  {
    "id": "127",
    "name": "Sherin Rajan Reumah",
    "role": "Charter Joint Secretary",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/reuan0/",
      "linkedin": "https://www.linkedin.com/in/sherin-rajan-reumah-788a53238?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      "facebook": ""
    },
    "image": "/coordinators/sherin-rajan-reumah.jpg"
  },
  {
    "id": "129",
    "name": "Ihsan Muhammed K P",
    "role": "Membership Chair",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/_.ih.s.an._?igsh=MXgxN3ppaDF6Y25ldQ==",
      "linkedin": "https://www.linkedin.com/in/ihsan-muhammed-k-p-a57004329?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      "facebook": ""
    },
    "image": "/coordinators/insan-muhammed-k-p.jpg"
  },
  {
    "id": "131",
    "name": "Aditya Saji",
    "role": "Sergeant at Arms",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/ramu_the_noob?igsh=MWlrcDBjZTgzN2pwbw==",
      "linkedin": "https://www.linkedin.com/in/aditya-saji-69643a284",
      "facebook": ""
    },
    "image": "/coordinators/aditya-saji.jpeg"
  },
  {
    "id": "133",
    "name": "Vyshnav S",
    "role": "Club Service Chair",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/vyshnav_7_7_7_5?igsh=dnoyamxyOWZrc28y",
      "linkedin": "https://www.linkedin.com/in/vyshnav-shyam-276a50329?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      "facebook": ""
    },
    "image": "/coordinators/vyshnav-s.jpg"
  },
  {
    "id": "138",
    "name": "Akash Chem J",
    "role": "Club Editor",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/akash_c.j?igsh=ZDJyeDE5YmJqYTh0",
      "linkedin": "https://www.linkedin.com/in/akash-chem-j-863925272?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      "facebook": ""
    },
    "image": "/coordinators/akas-chem-j.webp"
  },
  {
    "id": "140",
    "name": "Hrishikesh S Kumar",
    "role": "Social Media Chair",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/the_hrishi107?igsh=NnExam83OGYwZTU2",
      "linkedin": "https://www.linkedin.com/in/hrishikesh-s-kumar-7bb14b329?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      "facebook": ""
    },
    "image": "/coordinators/hrishikesh-s-kumar.jpg"
  },
  {
    "id": "142",
    "name": "Alestor Aldous",
    "role": "Web Service Chair",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "http://instagram.com/alestor_dev",
      "linkedin": "https://www.linkedin.com/in/alestor123/",
      "facebook": ""
    },
    "image": "/coordinators/alestor-aldous.jpg"
  },
  {
    "id": "143",
    "name": "Jesuin Peter",
    "role": "Community Service Chair",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/hey_jesuin?igsh=MWl2eHhoNnljMGhtcQ==",
      "linkedin": "https://www.linkedin.com/in/jesuin-peter-909013352?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      "facebook": ""
    },
    "image": "/coordinators/jesuin-peter.jpg"
  },
  {
    "id": "144",
    "name": "Abheerav A Nambiar",
    "role": "Charter President",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/abheerav_a_nambiar/",
      "linkedin": "https://www.linkedin.com/in/abheerav-anil-a97757328?utm_source=share_via&utm_content=profile&utm_medium=member_android",
      "facebook": ""
    },
    "image": "/coordinators/abheerav-a-nambiar.jpg"
  },
  {
    "id": "145",
    "name": "Ihsan Sanoj",
    "role": "Professional Service Chair",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/ihsansanoj10/",
      "linkedin": "https://www.linkedin.com/in/ihsan-sanoj-6a933a332/",
      "facebook": ""
    },
    "image": "/coordinators/ihsan-sanoj.jpg"
  },
  {
    "id": "146",
    "name": "Aaron Paul",
    "role": "International Service Chair",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "https://www.instagram.com/aaronpaul.xo/",
      "linkedin": "https://www.linkedin.com/in/aaron-paul-762248328/",
      "facebook": ""
    },
    "image": "/coordinators/aaron-paul-crop.JPG"
  },
  {
    "id": "147",
    "name": "Minu K K",
    "role": "Faculty incharge",
    "department": "",
    "year": "",
    "description": "",
    "social": {
      "instagram": "",
      "linkedin": "https://www.linkedin.com/in/minu-k-k-a7167456/",
      "facebook": ""
    },
    "image": "/coordinators/minu-k-k.jpeg"
  }
];

export const events: Event[] = [
  {
    "id": "2",
    "title": "Praathal: Serving Hope, One Breakfast at a Time",
    "description": "The Rotaract Club of Government Model Engineering College participated in Praathal, a community service initiative organized by Rotary Cochin Metropolis. Members served breakfast and tea to patients and caregivers at Government Medical College Hospital, Kalamassery, promoting compassion, service, and community engagement.",
    "date": "2026-05-21",
    "time": "7:00 AM",
    "location": "Government Medical College Hospital, Kalamassery",
    "category": "Community Service",
    "image": "/uploads/MBM_04088_2d3b7b2af9.JPG"
  },
  {
    "id": "6",
    "title": "A Day of Service, Smiles, and New perspectives at Kusumagiri Autism School",
    "description": "The Rotaract Club of Government Model Engineering College, in collaboration with Rotary Cochin Metropolis, visited Kusumagiri Autism School, Kakkanad, for a meaningful community service initiative.\n\nDuring the visit, a Solar Water Purifier was donated to the institution, and members spent quality time interacting with the students, sharing smiles, conversations, and memorable moments. The event highlighted the importance of empathy, inclusion, and understanding while reinforcing Rotaract's commitment to creating a positive impact through service.",
    "date": "2026-06-19",
    "time": "10:00 AM",
    "location": "Kusumagiri Autism School, Kakkanad",
    "category": "Community Service",
    "image": "/uploads/Whats_App_Image_2026_06_28_at_5_16_06_PM_ed28d83b15.jpeg"
  }
];

export const blogs: Blog[] = [
  {
    "id": "34",
    "title": "Installation Ceremony of Rotaract Club of Government Model Engineering College, Kochi",
    "author": "Rotaract Club MEC",
    "date": "2026-06-16",
    "content": "# Installation Ceremony of Rotaract Club of Government Model Engineering College, Kochi\n\nWhat began as an idea to bring together passionate students with a vision for service has now become a reality.\n\nThe official Installation Ceremony of the Rotaract Club of Government Model Engineering College, Kochi was successfully conducted on 16 May 2026 at the Internal Auditorium in the presence of distinguished guests, faculty members, and enthusiastic students.\n\nThe ceremony marked the beginning of a new journey focused on leadership, innovation, fellowship, and community service. Inspiring talks, the presentation of the club charter, and the installation of members highlighted the spirit of teamwork and commitment towards creating meaningful impact.\n\nThe event reflected the collective enthusiasm of students who aspire to serve society while growing as leaders. It laid the foundation for future projects, collaborations, and initiatives that will positively influence both the campus and the wider community.\n\nHere's to building a club that dreams big, serves wholeheartedly, and creates change together.\n",
    "excerpt": "The official installation of the Rotaract Club of Government Model Engineering College marked the beginning of a journey focused on leadership, fellowship, innovation, and community service.",
    "tags": [
      "Rotaract",
      "Installation",
      "Leadership",
      "MEC"
    ],
    "category": "Membership",
    "coverImage": "/uploads/IMG_9304_1a0dc27995.jpeg"
  },
  {
    "id": "35",
    "title": "Praathal: Serving Hope, One Breakfast at a Time",
    "author": "Rotaract Club of Government Model Engineering College, Kochi",
    "date": "2026-05-21",
    "content": "# Praathal: Serving Hope, One Breakfast at a Time\n\n**Date:** 21 May 2026\n**Time:** 7:00 AM\n**Venue:** Government Medical College Hospital, Kalamassery\n\nThe Rotaract Club of Government Model Engineering College, Kochi proudly participated in **Praathal**, a longstanding community service initiative organized by **Rotary Cochin Metropolis** on **21 May 2026** at the Government Medical College Hospital, Kalamassery.\n\nPraathal is a heartfelt initiative dedicated to providing breakfast and tea to patients and their caregivers at the hospital. For many families spending long hours by the bedside of their loved ones, a warm meal offers not only nourishment but also comfort and reassurance during challenging times.\n\nOur members joined hands with the Rotary Cochin Metropolis team in serving meals and interacting with beneficiaries, experiencing firsthand the profound impact that small acts of kindness can have. The event was a reminder that meaningful service often begins with simple gestures carried out with compassion and sincerity.\n\nWe are deeply grateful to **Rotary Cochin Metropolis** for providing us with the opportunity to contribute to this remarkable initiative. Collaborating on projects like Praathal strengthens our commitment to community service and reinforces the values that define the spirit of Rotaract.\n\nAs Rotaractors, we continue to believe that every act of service, no matter how small, has the power to create lasting change. Praathal was more than a service activity; it was an experience that reminded us of our shared responsibility to support and uplift those around us.\n\n**Service Above Self.**\n\n",
    "excerpt": "Rotaract MEC participated in Praathal, a community service initiative by Rotary Cochin Metropolis, serving breakfast and tea to patients and caregivers at Government Medical College Hospital, Kalamassery, reaffirming our commitment to service above self.",
    "tags": [
      "Praathal",
      "Community Service",
      "Rotary Cochin Metropolis",
      "Service Above Self",
      "Healthcare",
      "People of Action"
    ],
    "category": "Service",
    "coverImage": "/uploads/MBM_04261_9dff373e48.jpg"
  },
  {
    "id": "45",
    "title": "A Day of Service, Smiles, and New Perspectives at Kusumagiri Autism School",
    "author": "Rotaract Club of Government Model Engineering College, Kochi",
    "date": "2026-06-19",
    "content": "# A Day of Service, Smiles, and New Perspectives at Kusumagiri Autism School\n\n**Date:** 19 June 2026\n**Venue:** Kusumagiri Autism School, Kakkanad\n\nOn **19 June 2026**, members of the Rotaract Club of Government Model Engineering College, Kochi had the privilege of joining **Rotary Cochin Metropolis** for a meaningful day of service at **Kusumagiri Autism School, Kakkanad**.\n\nAs part of the visit, a **Solar Water Purifier** was donated to the institution, contributing to a healthier and more sustainable environment for the students and staff. Along with the donation, goodies were distributed, and our members spent quality time interacting with the children, creating moments filled with warmth, laughter, and genuine connection.\n\nFor many of our newly inducted Rotaractors, this was their first visit to an autism school. The experience offered valuable insights into the importance of empathy, acceptance, and inclusion. Beyond service, it became an opportunity to learn, understand, and appreciate the unique strengths and perspectives of every individual.\n\nThe visit served as a powerful reminder that meaningful community service is built not only through contributions and donations but also through compassion, respect, and human connection. Every conversation, smile, and shared moment reinforced the values that define the spirit of Rotaract.\n\nWe extend our sincere gratitude to **Rotary Cochin Metropolis** and the dedicated staff of **Kusumagiri Autism School** for welcoming us and allowing us to be part of this inspiring initiative. Experiences like these continue to strengthen our commitment to creating an inclusive and compassionate community.\n\nSome experiences do more than brighten a day. They transform perspectives, inspire empathy, and remind us that true service begins with understanding.\n\n**Service Above Self.**\n\n",
    "excerpt": "Rotaract MEC, in collaboration with Rotary Cochin Metropolis, visited Kusumagiri Autism School, Kakkanad, donating a Solar Water Purifier, spending time with the students, and embracing the values of empathy, inclusion, and meaningful community service.",
    "tags": [
      "Community Service",
      "Kusumagiri Autism School",
      "Rotary Cochin Metropolis",
      "Autism Awareness",
      "Inclusion",
      "People of Action",
      "Solar For Good",
      "Service Above Self"
    ],
    "category": "Service",
    "coverImage": "/uploads/Whats_App_Image_2026_06_28_at_5_16_06_PM_ed28d83b15.jpeg"
  }
];

export const activities: Activity[] = [];

export const introductions: any[] = [
  {
    "id": "13",
    "title": "About Rotaract Club of MEC Kochi",
    "vision": "Empower youth to become changemakers. Build inclusive and sustainable communities. Create lasting impact through service and leadership.",
    "mission": "To provide opportunities for Model Engineering College students to develop leadership skills, professional capabilities, and personal integrity through community service, innovative teamwork, and international fellowship.",
    "purpose": "Rotaract Club of Government Model Engineering College, Kochi (Rotaract MEC) is a community-driven student organization. We bring together energetic students who want to develop their professional and leadership skills while making a real difference in the lives of people around us. Our activities span educational support, environment conservation, technical skill development, and community welfare, all while cultivating lifelong friendships.",
    "history": "Officially installed in 2026, the Rotaract Club of Model Engineering College (Rotaract MEC) was established to channel student potential into meaningful societal change. Our foundation rests on the pillars of fellowship, leadership, and hands-on service. Through impact-driven community outreach, tailored professional development initiatives, and collaborative projects, we empower members to become proactive changemakers and empathetic leaders. As we expand our reach and adapt to new challenges, the club continues to grow dynamically, always guided by the timeless Rotary motto, \"Service Above Self.\"",
    "values": "[{\"title\":\"Service Above Self\",\"description\":\"Nurturing a spirit of volunteerism and placing community service at the core of all our initiatives.\"},{\"title\":\"Leadership\",\"description\":\"Empowering students with opportunities to take charge, guide teams, and develop project management skills.\"},{\"title\":\"Integrity\",\"description\":\"Fostering transparency, trust, and ethical responsibility in our relationships and execution of project activities.\"},{\"title\":\"Diversity\",\"description\":\"Welcoming students from all academic streams, interests, and backgrounds to foster a rich, inclusive environment.\"},{\"title\":\"Collaboration\",\"description\":\"Working hand-in-hand with Rotarians, other Rotaract clubs, local communities, and organizations for larger impact.\"},{\"title\":\"Innovation\",\"description\":\"Leveraging engineering expertise and creative design to create modern solutions for social and local problems.\"}]"
  }
];

export const members: Member[] = [];
